version: 2
updates:
- package-ecosystem: composer
  directory: /
  schedule:
    interval: weekly
  assignees:
  - jon-the-dev
  groups:
    composer-version:
      applies-to: version-updates
      patterns:
      - '*'
    composer-security:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: npm
  directory: /app
  schedule:
    interval: weekly
  assignees:
  - jon-the-dev
  groups:
    npm-version:
      applies-to: version-updates
      patterns:
      - '*'
    npm-security:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  assignees:
  - jon-the-dev
  groups:
    github-actions-version:
      applies-to: version-updates
      patterns:
      - '*'
    github-actions-security:
      applies-to: security-updates
      patterns:
      - '*'
